config/routes.rb
Rails.application.routes.draw do
  root to: "books#index"
  resources :books
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books =  Book.all
  end
  def show
    @book = Book.find(params[:id])
  end
  def new
    @book = Book.new
  end
  def create
    @book = Book.create(book_params)
    redirect_to book_path(@book)
  end
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  private
  def book_params
    params.require(:book).permit(:title, :author,:has_read)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/index.html.erb
<%= link_to "Create new Book", new_book_path %>
<ul>
  <% @books.each do |book| %>
    <li><%= link_to book.title, book_path(book) %></li>
  <% end %>
</ul>

app/views/books/new.html.erb
<h1>Create a new book</h1>

<%= form_for @book do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :has_read %>
  <%= f.check_box :has_read %>
  <%= f.submit %>
<% end %>

app/views/books/show.html.erb
<h2><%= @book.title %></h2>
<h3><%= @book.author %></h3>

<p>
You have
<%= "not" unless @book.has_read %>
read this book
</p>

<%= link_to "Delete", book_path(@book), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Goodreads</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>